index.html

Fixed version number and added a link to the release notes

Fix for Issue #4

---

index.html

I'm a writer who has been active in the Monero space for some time (MoneroEric.com), and thought I'd take a stab at writing some updated copy for the AEON homepage. 
* Reduced every-word capitalization of headings. Having Headings With All Capitals Like This really only reduces legibility, and does not help grab attention.
* Removed redundant copy throughout the page. While many altcoins like to add words in order to sound more technical and smart, in the end it really only confuses the new user and sounds awkward. The goal is to keep the words on the homepage as _simple_ as possible while still conveying the original meaning. Eg:
** Old sentence: "A tweak to use a 1 MB scratchpad allows AEON to run efficiently on lower end CPUs including some mobile processors as well as much better …

New copy for homepage

---

css/style.css
index.html

Slight html edit and improvements to CSS:
- For mobile/smallscreens: better styling
- For desktops: Icons in the "features" section were vertically aligned. 
- For desktops: better vertical centering above the fold
- Hover link color was darkened for better contrast
- Some cleanup of the stylesheet

Minor improvements to Aeon.cash styling

---

_layouts/default.html

I didn't add https://aeonblocks.com/ because it's down for at least more than one week.

add block explorers to footer

---

index.html

improve fast syncing statement

---

_layouts/default.html

- *added* TradeOgre, Bitliber & Letsdocoinz (Exchanges)
- *deleted* ChainRadar, MinerGate (Block explorers)
- *added* 162.210.173.150 / aeon.lol (Block explorers)
**preview** (*updated*)

update footer (block explorers and exchanges)

---

_layouts/default.html

add aeon funding system to navbar

---

_layouts/default.html

after testing this instant-exchange for the last few days, I think they should get added here too.
**preview**

add ChangeNOW to exchanges

---

index.html

add zipped press kit download link

---

index.html

add GUI downloads

---

_layouts/default.html

**BEFORE**
*width=960*
*width=992*
**AFTER**

fix banner-content responsive

---

_layouts/default.html

adding simpleswap linker to exchanges on Aeon.Cash

add SimpleSwap

---

_layouts/default.html

suggestion for #31 
**preview**

add email subscription

---

_layouts/default.html

Add in missing ChangeNow Aeon trading pair and also IRC link

Add ChangeNow pair, IRC, Discord, and Medium blog

---

_layouts/default.html

Add additional exchange service

Add Xchange.me

---

_config.yml
_includes/content.html
_includes/footer.html
_includes/header.html
_layouts/default.html
css/style.css
index.de.html
index.eo.html
index.es.html
index.pl.html
js/custom.js
readme.md

To start off with, this PR gives the website a slight structure overhaul. It does not change anything that appears on the front end, other than language switcher and language, when switched.
This pull request sections off the page header and footer from _layouts/default.html and places them into _includes/header.html and _includes/footer.html. They are included in the default layout. This will make it easier to find what areas of the page need edited. In addition to moving header and footer, I also placed the banner section directly in index.html. However, in the future, I believe it would be best to move this to it's own file as well. 
Multiple languages are now supported. As Github does not allow the use of unapproved plugins such as, jekyll-multiple-languages-plugin (same plugin Monero …

Structure update + additional language support

---

_config.yml

Polish language typos

---

_includes/footer.html

Add new block explorer https://aeonblockchecker.ninja

add new block explorer

---

readme.md

@mentions do not render in files like readme.md
also, @mentions is destroying line breaks

small readme.md fixes

---

_layouts/default.html

fix for introduced mess in #72

fix for wrong href's from no-external-scripts

---

_includes/header.html
css/style.css

language dropdown styling

---

_includes/footer.html

update exchange pairs to include common swap symbol

---

_config.yml
_includes/header.html
index.fr.html
readme.md

Add French Translations to website.
Thanks to estenity on Bitcointalk for the translations.

Add French translations

---

_includes/footer.html
_layouts/default.html

moved js file includes from footer.html to default.html where you can already find css file includes

move js files to default.html

---

_includes/footer.html

**offline:**
- https://bitliber.com/markets/aeon-btc
- https://bitliber.com/markets/aeon-xmr
- https://letsdocoinz.com/AEON-BTC
**aeon not available anymore:**
- https://changenow.io
- https://simpleswap.io
**added:**
- https://www.altilly.com/market/AEON_BTC
- https://aeon.to

update exchange list

---

_includes/footer.html

Added 2 explorers and update medium blog link

Update block explorers and medium link

---

_includes/footer.html

https://github.com/aeonix/aeon/pull/235

changed block explorer IP from 162.210.173.150 to 104.168.163.221

---

_includes/footer.html
readme.md

Update block explorers and Copywrite year

Update block explorer and Copywrite year

---

_layouts/downloads.html

#133 
update of hashes missing in this PR, paging @stoffu @aeonix

Update for v0.14.2.1 release

---

_includes/footer.html

Remove dead CryptoNote.org link

Footer: Remove dead CryptoNote.org link
